#!/usr/bin/env bash

die()
{
	printf '\e[31merror:\e[m %s\n' "$*" >&2
	exit 1
}

if (( $# )); then
	if [[ -e $1 ]]; then
		program=$(<"$1")
	else
		die "file '$1' does not exist"
	fi
else
	mapfile -t
	program=${MAPFILE[*]}
	[[ -c /dev/tty ]] && exec </dev/tty
fi

program=${program//[^'><+-.,[]']}
declare -A tape

for (( ptr = 0; index < ${#program}; index++ )); do
	case ${program:index:1} in
		'>')
			(( ptr++ ))
			;;
		'<')
			(( ptr-- ))
			;;
		'+')
			(( tape[$ptr]++ ))
			(( tape[$ptr] > 255 )) && tape[$ptr]=0
			;;
		'-')
			(( tape[$ptr]-- ))
			(( tape[$ptr] < 0 )) && tape[$ptr]=255
			;;
		'.')
			printf -v hex %x "${tape[$ptr]}"
			printf %b "\x$hex"
			;;
		',')
			[[ -z $input ]] && {
				mapfile -n 1
				input+=${MAPFILE[0]}
			}

			[[ -n ${MAPFILE[0]+x} ]] && {
				printf -v "tape[$ptr]" %d "'${input::1}"
				input=${input#?}
			}
			;;
		'[')
			if (( tape[$ptr] )); then
				stack+=("$index")
			else
				for (( depth = 1; depth > 0 && ++index; )); do
					case ${program:index:1} in
						'[') (( depth++ )) ;;
						']') (( depth-- )) ;;
						'') die "unmatched [" ;;
					esac
				done
			fi
			;;
		']')
			(( ${#stack[@]} )) || die "unmatched ]"

			(( tape[$ptr] )) && (( index = stack[-1] - 1 ))
			unset 'stack[-1]'
			;;
	esac
done
(( ${#stack[@]} )) && die "unmatched ["
