#!/usr/bin/env bash
#set -x

if (( $# )); then
	program=$(<"$1")
else
	mapfile -t
	program=${MAPFILE[*]}
fi

program=${program//[^'><+-.,[]']}

for (( index = 0; index < ${#program}; index++ )); do
	case ${program:index:1} in
		'>')
			(( ptr++ ))
			;;
		'<')
			(( ptr > 0 && ptr-- ))
			;;
		'+')
			(( tape[ptr]++ ))
			;;
		'-')
			(( tape[ptr]-- ))
			;;
		'.')
			printf -v hex %x "${tape[ptr]}"
			printf %b "\x$hex"
			;;
		',')
			[[ -z $input ]] && {
				mapfile -n 1
				[[ -z ${MAPFILE[0]+x} ]] && exit
				input+=${MAPFILE[0]}
			}

			printf -v 'tape[ptr]' %d "'${input::1}"
			input=${input#?}
			;;
		'[')
			if (( tape[ptr] )); then
				stack+=("$index")
			else
				for (( depth = 1; depth > 0 && ++index; )); do
					case ${program:index:1} in
						'[')
							(( depth++ ))
							;;
						']')
							(( depth-- ))
							;;
					esac

					(( index >= ${#program} )) && {
						printf "Error: Unmatched opening bracket\n"
						exit 1
					}
				done
			fi

			;;
		']')
			(( ${#stack[@]} == 0 )) && {
				printf "Error: Unmatched closing bracket\n"
				exit 1
			}

			(( tape[ptr] )) && (( index = stack[-1] - 1 ))
			unset 'stack[-1]'
			;;
	esac
done
